version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: usuariosdb
    volumes:
      - mongo_data:/data/db

  fastapi:
    build: .
    container_name: fastapi-app
    restart: always
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongo:27017/usuariosdb
      MONGO_DB: usuariosdb
    depends_on:
      - mongo

volumes:
  mongo_data:
